### ISSUE TITLE
Don't use `time.Duration`

### ISSUE THREAD

**Issue by vincentbernat** [gavv/monotime#2]
Hey!

I know this may be difficult to change now, but returning `time.Duration` for `Now()` has little interest since the result cannot be used with duration-related functions. This is a bit confusing. You should return something like `MonotonicTime`. But maybe this is hard to change now.

**Comment by sheerun** [comment]
I use something like:

```
var timeStart = time.Now()
var monoStart = monotime.Now()

func MonoTime() int64 {
	return timeStart.Add(monotime.Since(monoStart)).UnixNano()
}
```

**Comment by gavv** [comment]
Starting from Go 1.9, the standard time package transparently uses monotonic clocks when necessary, so this package is no longer relevant. I'm closing all issues and archiving the repo.
